# Generated by Django 3.0.3 on 2020-04-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200401_1641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tags',
            new_name='tag',
        ),
    ]
